CREATE TABLE IF NOT EXISTS public."TblLRPodcastEpisode" (
  "EpisodeID" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "EpisodeNo" integer NOT NULL,
  "Title" text NOT NULL,
  "ShortDescription" text,
  "Category" text,
  "SpotifyURL" text,
  "Transcript" text,
  "QuizURL" text,
  "IsPublished" boolean NOT NULL DEFAULT true,
  "CreatedAt" timestamptz NOT NULL DEFAULT now(),
  "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_TblLRPodcastEpisode_EpisodeNo" UNIQUE ("EpisodeNo"),
  CONSTRAINT "CK_TblLRPodcastEpisode_EpisodeNo" CHECK ("EpisodeNo" > 0),
  CONSTRAINT "CK_TblLRPodcastEpisode_ShortDescription"
    CHECK ("ShortDescription" IS NULL OR char_length("ShortDescription") <= 50)
);
